### ISSUE TITLE
Request for Access to Dataset and Pre-trained Model

### ISSUE THREAD

**Issue by Raindow** [lxirich/MM-Retinal#2]
Dear Author,
Thanks so much for open-sourcing your impressive work! It's a major step forward in the field of foundational models for retinal studies, and I’m really interested in following your progress.
However, I ran into some issues while trying to access the dataset and pre-trained model. The download link requires permission. Could you please grant access or maybe provide an alternative download method?
Thanks a lot for your help!

**Comment by lxirich** [comment]
Thanks for your attention! The download links for the MM-Retinal and pre-trained models are now available. You can download them at your convenience.

**Comment by Raindow** [comment]
Thank you so much for granting access to the dataset and pre-trained model. I really appreciate your prompt response and assistance.
